// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkTAP.Models;

namespace WorkTAP.Migrations
{
    [DbContext(typeof(PersonsContext))]
    [Migration("20210319130349_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorkTAP.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Nik",
                            Name = "Nikita"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Habib",
                            Name = "Alexandr"
                        });
                });

            modelBuilder.Entity("WorkTAP.Models.Skill", b =>
                {
                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint");

                    b.HasKey("PersonId", "Name");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Name = "C#",
                            Level = (byte)6
                        },
                        new
                        {
                            PersonId = 2,
                            Name = "PHP",
                            Level = (byte)3
                        });
                });

            modelBuilder.Entity("WorkTAP.Models.Skill", b =>
                {
                    b.HasOne("WorkTAP.Models.Person", null)
                        .WithMany("Skills")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkTAP.Models.Person", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
